workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 15
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
        working_directory: .
      - name: Build APK
        script: flutter build apk --release
        working_directory: .
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
