workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 15
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd .
          flutter pub get
      - name: Build APK
        script: |
          cd .
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
